package com.feedme.entity;
// Generated 2016-1-19 19:51:38 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Discuss generated by hbm2java
 */
public class Discuss implements java.io.Serializable {

	private Integer discussId;
	private User user;
	private String discussTitle;
	private String discussContent;
	private Date discussCreateTime;
	private int discussHot;
	private Set replies = new HashSet(0);

	public Discuss() {
	}

	public Discuss(User user, String discussTitle, String discussContent, Date discussCreateTime, int discussHot) {
		this.user = user;
		this.discussTitle = discussTitle;
		this.discussContent = discussContent;
		this.discussCreateTime = discussCreateTime;
		this.discussHot = discussHot;
	}

	public Discuss(User user, String discussTitle, String discussContent, Date discussCreateTime, int discussHot,
			Set replies) {
		this.user = user;
		this.discussTitle = discussTitle;
		this.discussContent = discussContent;
		this.discussCreateTime = discussCreateTime;
		this.discussHot = discussHot;
		this.replies = replies;
	}

	public Integer getDiscussId() {
		return this.discussId;
	}

	public void setDiscussId(Integer discussId) {
		this.discussId = discussId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getDiscussTitle() {
		return this.discussTitle;
	}

	public void setDiscussTitle(String discussTitle) {
		this.discussTitle = discussTitle;
	}

	public String getDiscussContent() {
		return this.discussContent;
	}

	public void setDiscussContent(String discussContent) {
		this.discussContent = discussContent;
	}

	public Date getDiscussCreateTime() {
		return this.discussCreateTime;
	}

	public void setDiscussCreateTime(Date discussCreateTime) {
		this.discussCreateTime = discussCreateTime;
	}

	public int getDiscussHot() {
		return this.discussHot;
	}

	public void setDiscussHot(int discussHot) {
		this.discussHot = discussHot;
	}

	public Set getReplies() {
		return this.replies;
	}

	public void setReplies(Set replies) {
		this.replies = replies;
	}

}
