package com.feedme.entity;
// Generated 2016-1-19 19:51:38 by Hibernate Tools 4.3.1.Final

/**
 * Memory generated by hbm2java
 */
public class Memory implements java.io.Serializable {

	private Integer memoryId;
	private User user;
	private Word word;
	private int memoryProficiency;
	private int memoryDifficulty;
	private int memoryImportant;
	private int memoryAccuracy;

	public Memory() {
	}

	public Memory(User user, Word word, int memoryProficiency, int memoryDifficulty, int memoryImportant,
			int memoryAccuracy) {
		this.user = user;
		this.word = word;
		this.memoryProficiency = memoryProficiency;
		this.memoryDifficulty = memoryDifficulty;
		this.memoryImportant = memoryImportant;
		this.memoryAccuracy = memoryAccuracy;
	}

	public Integer getMemoryId() {
		return this.memoryId;
	}

	public void setMemoryId(Integer memoryId) {
		this.memoryId = memoryId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Word getWord() {
		return this.word;
	}

	public void setWord(Word word) {
		this.word = word;
	}

	public int getMemoryProficiency() {
		return this.memoryProficiency;
	}

	public void setMemoryProficiency(int memoryProficiency) {
		this.memoryProficiency = memoryProficiency;
	}

	public int getMemoryDifficulty() {
		return this.memoryDifficulty;
	}

	public void setMemoryDifficulty(int memoryDifficulty) {
		this.memoryDifficulty = memoryDifficulty;
	}

	public int getMemoryImportant() {
		return this.memoryImportant;
	}

	public void setMemoryImportant(int memoryImportant) {
		this.memoryImportant = memoryImportant;
	}

	public int getMemoryAccuracy() {
		return this.memoryAccuracy;
	}

	public void setMemoryAccuracy(int memoryAccuracy) {
		this.memoryAccuracy = memoryAccuracy;
	}

}
