package com.feedme.entity;
// Generated 2016-1-19 19:51:38 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Reply generated by hbm2java
 */
public class Reply implements java.io.Serializable {

	private Integer replyId;
	private Discuss discuss;
	private User user;
	private String replyContent;
	private Date replyCreateTime;

	public Reply() {
	}

	public Reply(Discuss discuss, User user, String replyContent, Date replyCreateTime) {
		this.discuss = discuss;
		this.user = user;
		this.replyContent = replyContent;
		this.replyCreateTime = replyCreateTime;
	}

	public Integer getReplyId() {
		return this.replyId;
	}

	public void setReplyId(Integer replyId) {
		this.replyId = replyId;
	}

	public Discuss getDiscuss() {
		return this.discuss;
	}

	public void setDiscuss(Discuss discuss) {
		this.discuss = discuss;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getReplyContent() {
		return this.replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	public Date getReplyCreateTime() {
		return this.replyCreateTime;
	}

	public void setReplyCreateTime(Date replyCreateTime) {
		this.replyCreateTime = replyCreateTime;
	}

}
