package com.feedme.entity;
// Generated 2016-1-19 19:51:38 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String userAccount;
	private String userPassword;
	private String userName;
	private String userHead;
	private Date userCreateTime;
	private int userPoint;
	private Set memories = new HashSet(0);
	private Set replies = new HashSet(0);
	private Set discusses = new HashSet(0);
	private Set pets = new HashSet(0);

	public User() {
	}

	public User(String userAccount, String userPassword, String userName, String userHead, Date userCreateTime,
			int userPoint) {
		this.userAccount = userAccount;
		this.userPassword = userPassword;
		this.userName = userName;
		this.userHead = userHead;
		this.userCreateTime = userCreateTime;
		this.userPoint = userPoint;
	}

	public User(String userAccount, String userPassword, String userName, String userHead, Date userCreateTime,
			int userPoint, Set memories, Set replies, Set discusses, Set pets) {
		this.userAccount = userAccount;
		this.userPassword = userPassword;
		this.userName = userName;
		this.userHead = userHead;
		this.userCreateTime = userCreateTime;
		this.userPoint = userPoint;
		this.memories = memories;
		this.replies = replies;
		this.discusses = discusses;
		this.pets = pets;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserHead() {
		return this.userHead;
	}

	public void setUserHead(String userHead) {
		this.userHead = userHead;
	}

	public Date getUserCreateTime() {
		return this.userCreateTime;
	}

	public void setUserCreateTime(Date userCreateTime) {
		this.userCreateTime = userCreateTime;
	}

	public int getUserPoint() {
		return this.userPoint;
	}

	public void setUserPoint(int userPoint) {
		this.userPoint = userPoint;
	}

	public Set getMemories() {
		return this.memories;
	}

	public void setMemories(Set memories) {
		this.memories = memories;
	}

	public Set getReplies() {
		return this.replies;
	}

	public void setReplies(Set replies) {
		this.replies = replies;
	}

	public Set getDiscusses() {
		return this.discusses;
	}

	public void setDiscusses(Set discusses) {
		this.discusses = discusses;
	}

	public Set getPets() {
		return this.pets;
	}

	public void setPets(Set pets) {
		this.pets = pets;
	}

}
