package com.feedme.entity;
// Generated 2016-1-19 19:51:38 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Word generated by hbm2java
 */
public class Word implements java.io.Serializable {

	private Integer wordId;
	private String wordSpell;
	private String wordSpeech;
	private String wordMean;
	private String wordPhoneticSymbol;
	private String wordClassifyOfBook;
	private byte wordClassifyUnit;
	private String wordPicture;
	private String wordExample1;
	private String wordExample2;
	private String wordMeanOfExample1;
	private String wordMeanOfExample2;
	private Set memories = new HashSet(0);

	public Word() {
	}

	public Word(String wordSpell, String wordSpeech, String wordMean, String wordPhoneticSymbol,
			String wordClassifyOfBook, byte wordClassifyUnit, String wordPicture, String wordExample1,
			String wordExample2, String wordMeanOfExample1, String wordMeanOfExample2) {
		this.wordSpell = wordSpell;
		this.wordSpeech = wordSpeech;
		this.wordMean = wordMean;
		this.wordPhoneticSymbol = wordPhoneticSymbol;
		this.wordClassifyOfBook = wordClassifyOfBook;
		this.wordClassifyUnit = wordClassifyUnit;
		this.wordPicture = wordPicture;
		this.wordExample1 = wordExample1;
		this.wordExample2 = wordExample2;
		this.wordMeanOfExample1 = wordMeanOfExample1;
		this.wordMeanOfExample2 = wordMeanOfExample2;
	}

	public Word(String wordSpell, String wordSpeech, String wordMean, String wordPhoneticSymbol,
			String wordClassifyOfBook, byte wordClassifyUnit, String wordPicture, String wordExample1,
			String wordExample2, String wordMeanOfExample1, String wordMeanOfExample2, Set memories) {
		this.wordSpell = wordSpell;
		this.wordSpeech = wordSpeech;
		this.wordMean = wordMean;
		this.wordPhoneticSymbol = wordPhoneticSymbol;
		this.wordClassifyOfBook = wordClassifyOfBook;
		this.wordClassifyUnit = wordClassifyUnit;
		this.wordPicture = wordPicture;
		this.wordExample1 = wordExample1;
		this.wordExample2 = wordExample2;
		this.wordMeanOfExample1 = wordMeanOfExample1;
		this.wordMeanOfExample2 = wordMeanOfExample2;
		this.memories = memories;
	}

	public Integer getWordId() {
		return this.wordId;
	}

	public void setWordId(Integer wordId) {
		this.wordId = wordId;
	}

	public String getWordSpell() {
		return this.wordSpell;
	}

	public void setWordSpell(String wordSpell) {
		this.wordSpell = wordSpell;
	}

	public String getWordSpeech() {
		return this.wordSpeech;
	}

	public void setWordSpeech(String wordSpeech) {
		this.wordSpeech = wordSpeech;
	}

	public String getWordMean() {
		return this.wordMean;
	}

	public void setWordMean(String wordMean) {
		this.wordMean = wordMean;
	}

	public String getWordPhoneticSymbol() {
		return this.wordPhoneticSymbol;
	}

	public void setWordPhoneticSymbol(String wordPhoneticSymbol) {
		this.wordPhoneticSymbol = wordPhoneticSymbol;
	}

	public String getWordClassifyOfBook() {
		return this.wordClassifyOfBook;
	}

	public void setWordClassifyOfBook(String wordClassifyOfBook) {
		this.wordClassifyOfBook = wordClassifyOfBook;
	}

	public byte getWordClassifyUnit() {
		return this.wordClassifyUnit;
	}

	public void setWordClassifyUnit(byte wordClassifyUnit) {
		this.wordClassifyUnit = wordClassifyUnit;
	}

	public String getWordPicture() {
		return this.wordPicture;
	}

	public void setWordPicture(String wordPicture) {
		this.wordPicture = wordPicture;
	}

	public String getWordExample1() {
		return this.wordExample1;
	}

	public void setWordExample1(String wordExample1) {
		this.wordExample1 = wordExample1;
	}

	public String getWordExample2() {
		return this.wordExample2;
	}

	public void setWordExample2(String wordExample2) {
		this.wordExample2 = wordExample2;
	}

	public String getWordMeanOfExample1() {
		return this.wordMeanOfExample1;
	}

	public void setWordMeanOfExample1(String wordMeanOfExample1) {
		this.wordMeanOfExample1 = wordMeanOfExample1;
	}

	public String getWordMeanOfExample2() {
		return this.wordMeanOfExample2;
	}

	public void setWordMeanOfExample2(String wordMeanOfExample2) {
		this.wordMeanOfExample2 = wordMeanOfExample2;
	}

	public Set getMemories() {
		return this.memories;
	}

	public void setMemories(Set memories) {
		this.memories = memories;
	}

}
